### ISSUE TITLE
New script with new App not working

### ISSUE THREAD

**Issue by SchneHa** [fotosyn/berrycam#1]
Hi,
I installed the new app and updated the script to the latest version. Running the script produces the following error message:

```
pi@RPiTHREE ~/berrycam $ sudo nohup python3 berryCam.py > berryCam.log & tail -f berryCam.log
[1] 2827
nohup: ignoriere Eingabe und leite Standardfehlerausgabe auf Standardausgabe um
Traceback (most recent call last):
  File "berryCam.py", line 23, in <module>
    class BerryCamHandler (http.server.SimpleHTTPRequestHandler):
  File "berryCam.py", line 25, in BerryCamHandler
    print("B E R R Y C A M -- Listening on port ", port, flush=True)
TypeError: 'flush' is an invalid keyword argument for this function
```

What is wrong?

**Comment by fotosyn** [comment]
Hi @SchneHa can you check your version of Python 3 by using

python3 --version

If this is lower than 3.3 then perhaps upgrade your version (mine is at 3.7.3-1)

To do this try

sudo apt-get install python3

Let me know how it goes and I'll update the docs if need be 👍

**Comment by SchneHa** [comment]
OK, I did. Mine is 3.2.3 but I can’t upgrade. Using sudo apt-get install python3 I got the message that my version of python3 is already the newest.

**Comment by SchneHa** [comment]
I'm on Wheezy, maybe that's the reason why. There is no newer version of Python3 available for Wheezy.

**Comment by fotosyn** [comment]
OK thanks @SchneHa 

Can you also try:

```
sudo apt-get install python3.7
```

If this has no results, you can also try removing the `flush=true` from the BerryCam.py script.

This results in no verbose output to the command line telling you BerryCam is running and you'll get an stdout notice but it will allow you to capture images.

**Comment by fotosyn** [comment]
> I'm on Wheezy, maybe that's the reason why. There is no newer version of Python3 available for Wheezy.

I'm pretty sure you can still update to 3.7 with wheezy but let me know if this causes issues.

**Comment by fotosyn** [comment]
@SchneHa I have added a troubleshooting section to the getting started guide. Let me know if any of the solutions provided work for you and I'll close this issue.

https://github.com/fotosyn/berrycam#troubleshooting

**Comment by SchneHa** [comment]
`sudo apt-get install python3.7` failed, no such packet.

> If this has no success, you can also try removing the , flush=true on lines 25 and 26 from the BerryCam.py script.

That's what I tried first, it ran into another error:
```
pi@RPiTHREE ~/berrycam $ sudo nohup python3 berryCam.py > berryCam.log & tail -f berryCam.log
[1] 2760
nohup: ignoriere Eingabe und leite Standardfehlerausgabe auf Standardausgabe um
B E R R Y C A M -- Listening on port  8000
Please ensure your BerryCam App is installed and running on your iOS Device
Traceback (most recent call last):
  File "berryCam.py", line 99, in <module>
    with socketserver.TCPServer(("", port), BerryCamHandler) as httpd:
AttributeError: __exit__
```

**Comment by fotosyn** [comment]
Thanks @SchneHa looks like we are making some progress. I suspect that there might be a formatting error in the code. Couple things we can try now are deleting lines 25 and 26 altogether, or check that the preceding comma is removed that would have been in front of the flush=true parameter on those lines.

```
    print("B E R R Y C A M -- Listening on port ", port**, flush=True**)
    print("Please ensure your BerryCam App is installed and running on your iOS Device"**, flush=True**)
```

**Comment by SchneHa** [comment]
Comma is deleted!

**Comment by fotosyn** [comment]
Okay, can you try deleting lines 25 and 26 altogether?

**Comment by SchneHa** [comment]
See above, the result is the same:
```
  File "berryCam.py", line 99, in <module>
    with socketserver.TCPServer(("", port), BerryCamHandler) as httpd:
AttributeError: __exit__
```

**Comment by SchneHa** [comment]
`git clone https://github.com/fotosyn/berrycam.git`
No change.

**Comment by SchneHa** [comment]
Should I try [this](https://www.ramoonus.nl/2018/06/30/installing-python-3-7-on-raspberry-pi/)? I think it will take a while to see wether it works.

**Comment by fotosyn** [comment]
Yes I had to pop out but I was going to research that for you. It's most likely a Python version issue related to the HTTP server we are running.

Kudos to you if you follow those instructions and you get success. Let me know and I'll update the guide to reflect this.

Thanks!

**Comment by SchneHa** [comment]
OK, installation is finished. As I checked the version with `python -V` it says `Python 3.7.0`. I followed the instruction up to verification (without reverting!) and got the result `Python 3.7.0`. I changed the directory to ~/berrycam and tried `sudo nohup python3 berryCam.py > berryCam.log & tail -f berryCam.log` again. NO success, same errormessage (flush). I rebooted and checked `python3 --version` -> `Python 3.2.3`. `python -V` returns `Python 2.7.3`. The directory `Python-3.7.0` seems not to exist anymore.

Now, I'm trying to install 3.7.0 again.

**Comment by fotosyn** [comment]
Thanks @SchneHa i am now trying a build of Raspbian Jessie to see how I can get this to work on older Pi's

It would appear the quickest and easiest route is to install a new version of Raspberry Pi OS on the SD card but I'll see if this is a viable route.

**Comment by fotosyn** [comment]
Hi @SchneHa thanks for all your input and patience today. I have worked upon a solution which can be seen here in the Toubleshooting section.

https://github.com/fotosyn/berrycam#troubleshooting

**Comment by SchneHa** [comment]
SUCCES, That worked for me.
But now I have another problem: The latest version of BerryCam App isn't connecting. I had an older version of the App and updated. I see "Not connected" and if I tap the "..." Menu the screen is dark and no Menu appears.
What about launching the script if the RPi had a reboot. It would be nice if the script is launched automatically. Can you write a few sentences to this issue?

By the way: It's a very nice piece of software you created. I'm using it since the beginning! Thank you very much.

**Comment by fotosyn** [comment]
Can you send me a screengrab of the issue you're experiencing as well as details about the version of iOS and which type of device?

Thanks for your kind comments by the way.

**Comment by SchneHa** [comment]
iOS Version and device see edit of my last post.
![IMG_2064](https://user-images.githubusercontent.com/6528455/101941842-d95af380-3be8-11eb-9f0b-52debc577189.PNG)
![IMG_2065](https://user-images.githubusercontent.com/6528455/101941855-de1fa780-3be8-11eb-8546-d56b129a72be.PNG)

**Comment by fotosyn** [comment]
Sincere apologies @SchneHa i have now been able to recreate this issue. I will look into it as a priority and get a new version posted to the App Store.

**Comment by fotosyn** [comment]
I also have a way of auto-running BeeryCam at boot with some additional files. I will post guidance on how to do this in the support pages. I've had it running with success here for a while and my Pi's have been running continuously with it for a few months.

**Comment by SchneHa** [comment]
Thank you, I will wait for the new version.
Best regards,
Hans

**Comment by fotosyn** [comment]
Update with fixes submitted to the App Store. Thanks for all your help today 👍
