### ISSUE TITLE
Not accessible from the internet?

### ISSUE THREAD

**Issue by SchneHa** [fotosyn/berrycam#2]
Now, in actual version (debugged for iPhone SE and 8) I can access Pi's camera from local network, but not from internet as it was possible with the older version. 
Filling in my public IP address works, but not my DynDNS address.

**Comment by SchneHa** [comment]
Autostart the script after rebooting the Pi:
`sudo nano /etc/rc.local`
before line
`exit 0`
insert:
`sudo nohup python3 /home/pi/berrycam/berryCam.py > berryCam.log & tail -f berryCam.log &`
press ^X
press Y

**Comment by fotosyn** [comment]
Thanks @SchneHa yep that's pretty much what I've been doing here as well with rc.local

Can you give me more detail info@fotosyn.com in relation to your comments re accessing Pis outside of local network? 

If anything I would think port forwarding would still be working?

**Comment by SchneHa** [comment]
Any news about the internet access problem?

**Comment by fotosyn** [comment]
Still to investigate. I don't have a Pi set up with an external IP address at the moment but will try sometime next week.

**Comment by fotosyn** [comment]
Hi @SchneHa I have checked this out using my internet router and Google Wifi to test port forwarding, and all appears to be working as expected. 

If I access on my 4G network on my iPhone, connecting to the external port it connects to my Pi on the LAN and allows for image capture. I have tested this particular connection with a couple of friends and they have been able to connect and capture also.

I am not entirely up to speed with DynDNS - if you can contact me about this at info@fotosyn.com I can maybe look a bit more into this. It might be better to discuss this 1-1 for obvious reasons. 

Merry Christmas

-- Jim

**Comment by SchneHa** [comment]
Hi Jim,

did you find my PM? 

Best regards and Happy New Year,
Hans

**Comment by fotosyn** [comment]
Got them now Hans thank you. I'll check this connection later. The app doesn't insert www so it may be an issue with the network connection. Let me have a look 👌

**Comment by fotosyn** [comment]
What port number are you using? Is it 20?

**Comment by SchneHa** [comment]
8000
